### ISSUE TITLE
channelByName finds only one channel

### ISSUE THREAD

**Issue by soanaphikeste** [Rantanen/node-mumble#51] opened 2015-08-01 17:32 UTC
When there are multiple channels with the same name, `channelByName` will only return one of them. 

For example this is a valid channel structure (at least the official client allows it to be created):

    -Root
        -Test1
            - A
        - Test2
            - A

Then calling `myMumbleConnection.channelByName("A")` will return `/Root/Test 1/A`, but not `/Root/Test 2/A`.

**Comment by Rantanen** [comment] 2015-08-01 18:01
This is by design. While not optimal, it's far more confusing for a function to suddenly change from returning a single value to returning an array based on server admin adding/renaming channels.

Added `channelByPath()` to MumbleClient. You can use this with:

```
// Get the root channel
var root = client.channelByPath( '/' );

// Get the Root > Test2 > A channel
var test2a = client.channelByPath( '/Test2/A' );
```

If you need something else, you can always build your own lookup routines on top of the client.rootChannel and Channel.children collection.

**Comment by soanaphikeste** [comment] 2015-08-01 18:47
Thank you :)

**Comment by Prior99** [comment] 2015-08-03 06:20
I don't know. I think it is a better idea to always return an array, if there is only one channel with the specified name, return an array with only one item. But returning only one channel when there are multiple channels without having defined behaviour which one will be returned sounds like bad design.

**Comment by Rantanen** [comment] 2015-08-10 19:08
Yeah. I'm guessing the `channelByPath` fixed this. If not, there's always the `Channel.children` collection. Closing this.

**Closed by Rantanen** 2015-08-10 19:08 UTC
